== このリポジトリについて
OpenShift Virtualization Roadshowコンテンツの日本語訳リポジトリです。

英語版オリジナルのリポジトリは下記です。

https://github.com/rhpds/ocp4-getting-started-showroom

== 日本語化の方法
環境のBastion端末にSSHログイン後、端末で以下のコマンドを実行ください。

[source,bash,role=execute,subs="attributes"]
----
curl -sSL https://raw.githubusercontent.com/loungeplus/openshift-ws2/refs/heads/main/translation.sh | bash
----

# OpenShift Getting Started Workshop

## Overview
|===
|対象者の経験レベル
|初級

|平均所要時間
|90分
|===

このワークショップでは、開発者の視点から https://openshift.com[OpenShift] の使い方を実践的に学ぶことを目的としています。

https://www.redhat.com/en/topics/containers/whats-a-linux-container-vb[コンテナ] は、アプリケーションとそのすべての依存関係をパッケージ化する標準化された方法です。これにより、デプロイメントが簡素化され、デリバリーが迅速化されます。仮想マシンとは異なり、コンテナはオペレーティングシステムにバンドルされません。コンテナ内には、アプリケーション、ランタイム、ライブラリ、および構成のみがパッケージ化されます。そのため、コンテナは仮想マシンと比較して軽量で、移植性が高く、効率的です。

プロジェクトを迅速に開始したい開発者にとって、OpenShift は合理化されたワークフローと検証済みの統合を通じて、効率的なアプリケーション開発を可能にします。

### 目標

* OpenShift コマンドライン (CLI) と Web コンソールの使用。
* 既存のコンテナイメージを使用してアプリケーションをデプロイする。
* アプリケーションラベルを使用してコンポーネントを識別する。
* Webトラフィックを処理できるようにアプリケーションをスケールアップする。
* クラスター外のユーザーにアプリケーションを公開する。
* アプリケーションによって生成されたログを表示および操作する。
* アプリケーションコンテナにアクセスし、操作する。
* 他のユーザーにアプリケーションで共同作業するためのアクセス権を付与する。
* Gitリポジトリ内のソースコードからアプリケーションをデプロイする。
* OpenShift Developer Catalogからデータベースをデプロイする。
* アプリケーションがデータベースにアクセスできるように構成する。
* Web Hooksを設定して、アプリケーションの自動ビルドを有効にする。
* デプロイするアプリケーションで使用される特定のプログラミング言語に関連する追加のトピックも取り上げられる場合があります。

## Documentation

To test and develop this content locally, you can use a pre-built container with Podman or Docker as shown below.

[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

> Note: If using a rootless podman replace `-v $PWD:/antora` with `-v $PWD:/antora:z`

